routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->home();
});

Route::group(['middleware' => ['auth', 'auth.lock']], function () {
    Route::get('home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('users', App\Http\Controllers\UserController::class)->except(['show']);
    Route::get('users/{user}/change-password', [App\Http\Controllers\UserController::class, 'changePassword'])->name('users.password');
    Route::put('users/{user}/change-password', [App\Http\Controllers\UserController::class, 'updatePassword']);
    Route::get('users/{user}/role', [App\Http\Controllers\UserRoleController::class, 'edit'])->name('users.role');
    Route::put('users/{user}/role', [App\Http\Controllers\UserRoleController::class, 'update']);

    Route::get('profile', App\Http\Controllers\ProfileController::class)->name('profile');
    Route::get('change-password', [App\Http\Controllers\ProfileController::class, 'password'])->name('change-password');

    Route::resource('roles', \App\Http\Controllers\RoleController::class);

    Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
        Route::get('application', App\Http\Controllers\Settings\ApplicationController::class)->name('application');
        Route::put('application', [App\Http\Controllers\Settings\ApplicationController::class, 'update'])->name('application.update');
        Route::put('application/logo', [App\Http\Controllers\Settings\ApplicationController::class, 'updateLogo'])->name('application.update.logo');
        Route::put('application/icon', [App\Http\Controllers\Settings\ApplicationController::class, 'updateIcon'])->name('application.update.icon');
    });

    Route::get('lock', [\App\Http\Controllers\Auth\LockController::class, 'lock'])->name('auth.lock');
    Route::post('unlock', [\App\Http\Controllers\Auth\LockController::class, 'unlock'])->name('auth.unlock')->withoutMiddleware('auth.lock');
    Route::get('locked', \App\Http\Controllers\Auth\LockController::class)->name('auth.locked')->withoutMiddleware('auth.lock');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravolt\Avatar\Facade as Avatar;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getAvatarAttribute()
    {
        return Avatar::create($this->name)->toBase64();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserPasswordRequest;
use App\Http\Requests\UserRequest;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(User::class);
    }

    public function index()
    {
        $users = User::all();

        return view('users.index', compact('users'));
    }

    public function create()
    {
        $roles = Role::all();

        return view('users.create', compact('roles'));
    }

    public function store(UserRequest $request)
    {
        /** @var User $user */
        $user = User::create([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => Hash::make($request->input('password')),
        ]);

        $user->assignRole($request->input('role'));

        flash()->success('Successfully added new users');

        return redirect()->route('users.index');
    }

    public function edit(User $user)
    {
        $roles = Role::all();

        return view('users.edit', compact('user', 'roles'));
    }

    public function update(UserRequest $request, User $user)
    {
        $user->update([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
        ]);

        flash()->success('Successfully updated users');

        return redirect()->route('users.index');
    }

    public function changePassword(Request $request, User $user)
    {
        Gate::authorize('changePassword', $user);

        if ($request->user()->is($user)) {
            return redirect()->route('change-password');
        }

        return view('users.password', compact('user'));
    }

    public function updatePassword(UserPasswordRequest $request, User $user)
    {
        Gate::authorize('changePassword', $user);

        $user->forceFill([
            'password' => Hash::make($request->input('password'))
        ]);

        flash()->success('Password updated successfully');

        return redirect()->route('users.edit', $user);
    }

    public function destroy(User $user)
    {
        $user->delete();

        flash()->success('User deleted successfully');

        return redirect()->route('users.index');
    }
}

resources/views/users/assign-role.blade.php
@extends('layouts.app')

@section('title', __('Assign User Role'))

@section('content')
  <div class="row">
    <div class="col-lg-6">
      <div class="card-box">
        <h4 class="header-title mt-0">Assign User Role</h4>

        <p class="text-muted font-13">Set the user role in the application.</p>

        <form action="{{ route('users.role', $user) }}" method="post">
          @csrf
          @method('PUT')
          <div class="row">
            <div class="col-8">
              <div class="form-group">
                <label for="role" class="control-label">Select Role</label>
                <select id="role" name="role" class="custom-select">
                  @foreach ($roles as $role)
                    <option value="{{ $role->id }}" {{ $user->hasRole($role) ? 'selected' : '' }}>{{ $role->name }}</option>
                  @endforeach
                </select>
              </div>
            </div>
          </div>

          <button type="submit" class="btn btn-primary">Save</button>
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/users/create.blade.php
@extends('layouts.app')

@section('title', __('Create a New User'))

@section('content')
  <div class="row">
    <div class="col-lg-6">
      <div class="card-box">
        <h4 class="header-title mt-0">Profile Information</h4>

        <p class="text-muted font-13">Complete the user account profile information and email address.</p>

        <form action="{{ route('users.store') }}" method="post">
          @csrf
          <div class="row">
            <div class="col-lg-8">
              <div class="form-group">
                <label for="name" class="control-label">Name</label>
                <input type="text" id="name" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}" autofocus>
                @error('name')
                  <div class="invalid-feedback">
                    {{ $message }}
                  </div>
                @enderror
              </div>

              <div class="form-group">
                <label for="email" class="control-label">Email</label>
                <input type="email" id="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email') }}">
                @error('email')
                  <div class="invalid-feedback">
                    {{ $message }}
                  </div>
                @enderror
              </div>

              <h4 class="header-title mt-4">Assigned Role</h4>

              <p class="text-muted font-13">Set the user role in the application.</p>

              <div class="form-group">
                <label for="role" class="control-label">Select Role</label>
                <select id="role" name="role" class="custom-select @error('role') is-invalid @enderror">
                  @foreach ($roles as $role)
                    <option value="{{ $role->id }}"
                      {{ !old('role') && $role->name == \App\Models\Role::USER ? 'selected' : '' }}
                      {{ old('role') == $role->id ? 'selected' : '' }}
                    >{{ $role->name }}</option>
                  @endforeach
                </select>
                @error('role')
                  <div class="invalid-feedback">
                    {{ $message }}
                  </div>
                @enderror
              </div>

              <h4 class="header-title mt-4">Security</h4>

              <p class="text-muted font-13">Ensure your account is using a long, random password to stay secure.</p>

              <div class="form-group">
                <label for="password" class="control-label">Password</label>
                <input type="password" id="password" name="password" class="form-control @error('password') is-invalid @enderror">
                @error('password')
                  <div class="invalid-feedback">
                    {{ $message }}
                  </div>
                @enderror
              </div>

              <div class="form-group">
                <label for="password_confirmation" class="control-label">Password Confirmation</label>
                <input type="password" id="password_confirmation" name="password_confirmation" class="form-control @error('password_confirmation') is-invalid @enderror">
                @error('password_confirmation')
                  .invalid-feedback
                @enderror
              </div>
            </div>
          </div>

          <button type="submit" class="btn btn-primary">Save</button>
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title', $user->name)

@section('content')
  <div class="row">
    <div class="col-lg-6">
      <div class="card-box">
        <h4 class="header-title mt-0">Profile Information</h4>

        <p class="text-muted font-13">Update your account's profile information and email address.</p>

        <form action="{{ route('users.update', $user) }}" method="post">
          @csrf
          @method('PUT')
          <div class="row">
            <div class="col-lg-8">
              <div class="form-group">
                <label for="id" class="control-label">User ID</label>
                <input type="text" id="id" class="form-control" value="{{ $user->id }}" disabled>
              </div>

              <div class="form-group">
                <label for="name" class="control-label">Name</label>
                <input type="text" id="name" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name', $user->name) }}" autofocus>
                @error('name')
                  <div class="invalid-feedback">
                    {{ $message }}
                  </div>
                @enderror
              </div>

              <div class="form-group">
                <label for="email" class="control-label">Email</label>
                <input type="email" id="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email', $user->email) }}">
                @error('email')
                  <div class="invalid-feedback">
                    {{ $message }}
                  </div>
                @enderror
              </div>
            </div>
          </div>

          <button type="submit" class="btn btn-primary">Save</button>
        </form>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class="card-box">
        <h4 class="header-title mt-0">Assigned Role</h4>

        <p class="text-muted font-13">Set the user role in the application.</p>

        <div class="row">
          <div class="col-6">
            <div class="form-group">
              <label for="id" class="control-label">Current Role</label>
              <input type="text" class="form-control" value="{{ $user->roles->pluck('name')->join(', ') }}" disabled>
            </div>
          </div>
        </div>

        <a href="{{ route('users.role', $user) }}" class="btn btn-primary">Change Role</a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class="card-box">
        <h4 class="header-title mt-0">Security</h4>

        <p class="text-muted font-13">Ensure your account is using a long, random password to stay secure.</p>

        <a href="{{ route('users.password', $user) }}" class="btn btn-primary">Change Password</a>
      </div>
    </div>
  </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title', __('User Management'))

@push('css')
  <style>
    .table > tbody > tr > td {
      vertical-align: middle;
    }
  </style>
@endpush

@section('content')
  <div class="row">
    <div class="col-lg-12">
      <div class="card-box">
        <div class="dropdown float-right">
          <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown" aria-expanded="false">
            <i class="mdi mdi-dots-vertical"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <!-- item-->
            <a href="{{ route('users.create') }}" class="dropdown-item">Add a New User</a>
          </div>
        </div>

        <h4 class="header-title mt-0">{{ __('User Lists') }}</h4>

        <p class="text-muted font-13">User management and manage assigned roles.</p>

        <table id="datatable-users" class="table mb-0">
          <thead>
          <tr>
            <th style="width: 50px;">ID</th>
            <th style="width: 300px;">Name</th>
            <th style="width: 300px;">Email</th>
            <th style="width: 200px;">Role</th>
            <th style="width: 150px;">Date Created</th>
            <th>&nbsp;</th>
          </tr>
          </thead>
          <tbody>
          @foreach ($users as $user)
          <tr>
            <td>{{ $user->id }}</td>
            <td>
              <img src="{{ $user->avatar }}" class="rounded-circle avatar-sm mr-2" alt="{{ $user->name }} Avatar's">
              {{ $user->name }}
            </td>
            <td><a href="mailto:{{ $user->name }}<{{ $user->email }}>">{{ $user->email }}</a></td>
            <td>{{ $user->roles->pluck('name')->join(', ') ?? '-' }}</td>
            <td>{{ $user->created_at->format('Y-m-d') }}</td>
            <td>
              @canany(['update', 'changePassword', 'delete'], $user)
              <div class="dropdown float-right show">
                <a class="btn btn-primary dropdown-toggle d-none d-lg-block" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Action <i class="mdi mdi-chevron-down"></i>
                </a>

                <a href="#" class="dropdown-toggle arrow-none card-drop d-lg-none" data-toggle="dropdown" aria-expanded="false">
                  <i class="mdi mdi-dots-vertical"></i>
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                  @can('update', $user)
                    <a class="dropdown-item" href="{{ route('users.edit', $user) }}">Edit Profile</a>
                  @endcan

                  @can('changePassword', $user)
                    <a class="dropdown-item" href="{{ route('users.password', $user) }}">Change Password</a>
                  @endcan

                  @can('delete', $user)
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-danger" href="{{ route('users.destroy', $user) }}" data-method="delete" data-confirm="Are you sure?">Delete</a>
                  @endcan
                </div>
              </div>
              @endcanany
            </td>
          </tr>
          @endforeach
          </tbody>
        </table>

      </div>
    </div>
  </div>
@endsection

resources/views/users/password.blade.php
@extends('layouts.app')

@section('title', __('Change Password') . ' - ' . $user->name)

@section('content')
  <div class="row">
    <div class="col-lg-6">
      <div class="card-box">

        <h4 class="header-title mt-0">Change Password</h4>

        <p class="text-muted font-13">Ensure your account is using a long, random password to stay secure.</p>

        <form action="{{ route('users.password', $user) }}" method="post">
          @csrf
          @method('PUT')
          <div class="row">
            <div class="col-lg-8">
              <div class="form-group">
                <label for="password" class="control-label">Password</label>
                <input type="password" id="password" name="password" class="form-control @error('password') is-invalid @enderror" autofocus>
                @error('password')
                  <div class="invalid-feedback">
                    {{ $message }}
                  </div>
                @enderror
              </div>

              <div class="form-group">
                <label for="password_confirmation" class="control-label">Password Confirmation</label>
                <input type="password" id="password_confirmation" name="password_confirmation" class="form-control @error('password_confirmation') is-invalid @enderror">
                @error('password_confirmation')
                  <div class="invalid-feedback">
                    {{ $message }}
                  </div>
                @enderror
              </div>
            </div>
          </div>

          <button type="submit" class="btn btn-primary">Save</button>
        </form>
      </div>
    </div>
  </div>
@endsection