routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->home();
});

Route::group(['middleware' => ['auth', 'auth.lock']], function () {
    Route::get('home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('users', App\Http\Controllers\UserController::class)->except(['show']);
    Route::get('users/{user}/change-password', [App\Http\Controllers\UserController::class, 'changePassword'])->name('users.password');
    Route::put('users/{user}/change-password', [App\Http\Controllers\UserController::class, 'updatePassword']);
    Route::get('users/{user}/role', [App\Http\Controllers\UserRoleController::class, 'edit'])->name('users.role');
    Route::put('users/{user}/role', [App\Http\Controllers\UserRoleController::class, 'update']);

    Route::get('profile', App\Http\Controllers\ProfileController::class)->name('profile');
    Route::get('change-password', [App\Http\Controllers\ProfileController::class, 'password'])->name('change-password');

    Route::resource('roles', \App\Http\Controllers\RoleController::class);

    Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
        Route::get('application', App\Http\Controllers\Settings\ApplicationController::class)->name('application');
        Route::put('application', [App\Http\Controllers\Settings\ApplicationController::class, 'update'])->name('application.update');
        Route::put('application/logo', [App\Http\Controllers\Settings\ApplicationController::class, 'updateLogo'])->name('application.update.logo');
        Route::put('application/icon', [App\Http\Controllers\Settings\ApplicationController::class, 'updateIcon'])->name('application.update.icon');
    });

    Route::get('lock', [\App\Http\Controllers\Auth\LockController::class, 'lock'])->name('auth.lock');
    Route::post('unlock', [\App\Http\Controllers\Auth\LockController::class, 'unlock'])->name('auth.unlock')->withoutMiddleware('auth.lock');
    Route::get('locked', \App\Http\Controllers\Auth\LockController::class)->name('auth.locked')->withoutMiddleware('auth.lock');
});

app/Http/Controllers/Settings/ApplicationController.php
<?php

namespace App\Http\Controllers\Settings;

use App\Rules\CropperRule;
use App\Settings\ApplicationSetting;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Constraint;
use Intervention\Image\Facades\Image;

class ApplicationController
{
    public function __invoke(ApplicationSetting $setting)
    {
        return view('settings.application.index', compact('setting'));
    }

    public function update(Request $request, ApplicationSetting $setting)
    {
        $setting->name = $request->input('name');
        $setting->tagline = $request->input('name');
        $setting->save();

        flash()->success('Successfully updated application settings');

        return back();
    }

    public function updateLogo(Request $request, ApplicationSetting $setting)
    {
        $request->validate([
            'logo' => 'required|image',
            'crop' => ['required', 'json', new CropperRule],
        ]);

        $crop = json_decode($request->input('crop'), true);

        $image = Image::make($request->file('logo'));
        $image->rotate(360 - $crop['rotate']);
        $image->crop((int)$crop['width'], (int)$crop['height'], (int)$crop['x'], (int)$crop['y']);
        $image->resize(675, 110, function (Constraint $constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        });
        $image->save();

        $request->file('logo')->storePubliclyAs('logo', 'logo.png', ['disk' => 'public']);

        $setting->logo = 'storage/logo/logo.png';
        $setting->save();

        flash()->success('Successfully updated logo');

        return back();
    }

    public function updateIcon(Request $request, ApplicationSetting $setting)
    {
        $request->validate([
            'icon' => 'required|image',
            'crop' => ['required', 'json', new CropperRule],
        ]);

        $crop = json_decode($request->input('crop'), true);

        $image = Image::make($request->file('icon'));
        $image->rotate(360 - $crop['rotate']);
        $image->crop((int)$crop['width'], (int)$crop['height'], (int)$crop['x'], (int)$crop['y']);
        $image->resize(120, 120, function (Constraint $constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        });
        $image->save();

        $request->file('icon')->storePubliclyAs('icon', 'icon.png', ['disk' => 'public']);

        $setting->icon = 'storage/icon/icon.png';
        $setting->save();

        flash()->success('Successfully updated icon');

        return back();
    }
}

resources/views/settings/application/index.blade.php
@extends('layouts.app')

@section('title', 'Application Settings')

@section('content')
  <div class="row">
    <div class="col-lg-6">
      <div class="card-box">

        <h4 class="header-title mt-0">General Settings</h4>

        <p class="text-muted font-13">{{ __('messages.descriptions.Application Settings') }}</p>

        <form action="{{ route('settings.application.update') }}" method="post">
          @csrf
          @method('PUT')
          <div class="form-group">
            <label for="name" class="control-label">Application Name</label>
            <input type="text" id="name" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name', $setting->name) }}">
            @error('name')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>

          <div class="form-group">
            <label for="description" class="control-label">Description</label>
            <input type="text" id="description" name="description" class="form-control @error('description') is-invalid @enderror" value="{{ old('description', $setting->description) }}">
            @error('description')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
            @enderror
          </div>

          <button type="submit" class="btn btn-primary">Save</button>
        </form>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class="card-box">

        <h4 class="header-title mt-0">Logo Settings</h4>

        <p class="text-muted font-13">{{ __('messages.descriptions.Application Settings') }}</p>

        <img src="{{ asset($setting->logo) }}" alt="logo" class="img" style="width: 200px">

        <p class="mt-2">Recommendation Size : 135 x 22 pixels</p>

        <button type="button" class="btn btn-primary btn-change-logo">Change Logo</button>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class="card-box">

        <h4 class="header-title mt-0">Icon Settings</h4>

        <p class="text-muted font-13">{{ __('messages.descriptions.Application Settings') }}</p>

        <img src="{{ asset($setting->icon) }}" alt="logo" class="img" style="width: 37px">

        <p class="mt-2">Recommendation Size : 32 x 32 pixels</p>

        <button type="button" class="btn btn-primary btn-change-icon">Change Icon</button>
      </div>
    </div>
  </div>

  <!-- Logo Settings modal -->
  <div id="logo-setting-modal" class="modal fade img-cropper" tabindex="-1" role="dialog" aria-labelledby="logo-setting-modal-label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="logo-setting-modal-label">Change Logo</h4>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
          <form action="{{ route('settings.application.update.logo') }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <input type="file" id="input-logo" name="logo" accept="image/png" style="display: none;">
            <input type="hidden" class="crop-result" name="crop">

            <div class="if-image-exists" style="display: none;">
              <div class="img-container">
                <img class="output" alt="Cropping" src="">
              </div>

              <div class="btn-group">
                <button type="button" class="btn btn-primary btn-rotate"><i class="zmdi zmdi-rotate-right"></i> Putar</button>
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-light waves-effect" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-primary waves-effect waves-light btn-submit">Upload and Save</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

  <!-- Icon Settings modal -->
  <div id="icon-setting-modal" class="modal fade img-cropper-icon" tabindex="-1" role="dialog" aria-labelledby="logo-setting-modal-label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="logo-setting-modal-label">Change Icon</h4>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
          <form action="{{ route('settings.application.update.icon') }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <input type="file" id="input-icon" name="icon" accept="image/png" style="display: none;">
            <input type="hidden" class="crop-result" name="crop">

            <div class="if-image-exists" style="display: none;">
              <div class="img-container" style="width: 200px; height: 200px;">
                <img class="output" alt="Cropping" src="">
              </div>

              <div class="btn-group">
                <button type="button" class="btn btn-primary btn-rotate"><i class="zmdi zmdi-rotate-right"></i> Putar</button>
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-light waves-effect" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-primary waves-effect waves-light btn-submit">Upload and Save</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
@endsection

@push('css')
  <style>
    .img-container {
      margin: 10px 0;
    }

    .img-container img {
      /* This rule is very important, please don't ignore this */
      max-width: 100%;
    }

    .if-image-exists {
      display: none;
    }
  </style>
@endpush