routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->home();
});

Route::group(['middleware' => ['auth', 'auth.lock']], function () {
    Route::get('home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('users', App\Http\Controllers\UserController::class)->except(['show']);
    Route::get('users/{user}/change-password', [App\Http\Controllers\UserController::class, 'changePassword'])->name('users.password');
    Route::put('users/{user}/change-password', [App\Http\Controllers\UserController::class, 'updatePassword']);
    Route::get('users/{user}/role', [App\Http\Controllers\UserRoleController::class, 'edit'])->name('users.role');
    Route::put('users/{user}/role', [App\Http\Controllers\UserRoleController::class, 'update']);

    Route::get('profile', App\Http\Controllers\ProfileController::class)->name('profile');
    Route::get('change-password', [App\Http\Controllers\ProfileController::class, 'password'])->name('change-password');

    Route::resource('roles', \App\Http\Controllers\RoleController::class);

    Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
        Route::get('application', App\Http\Controllers\Settings\ApplicationController::class)->name('application');
        Route::put('application', [App\Http\Controllers\Settings\ApplicationController::class, 'update'])->name('application.update');
        Route::put('application/logo', [App\Http\Controllers\Settings\ApplicationController::class, 'updateLogo'])->name('application.update.logo');
        Route::put('application/icon', [App\Http\Controllers\Settings\ApplicationController::class, 'updateIcon'])->name('application.update.icon');
    });

    Route::get('lock', [\App\Http\Controllers\Auth\LockController::class, 'lock'])->name('auth.lock');
    Route::post('unlock', [\App\Http\Controllers\Auth\LockController::class, 'unlock'])->name('auth.unlock')->withoutMiddleware('auth.lock');
    Route::get('locked', \App\Http\Controllers\Auth\LockController::class)->name('auth.locked')->withoutMiddleware('auth.lock');
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;

class Role extends \Spatie\Permission\Models\Role
{
    use HasFactory;

    const ADMINISTRATOR = 'Administrator';
    const READONLY = 'Read Only';
    const USER = 'User';
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RoleRequest;
use App\Models\Permission;
use App\Models\Role;

class RoleController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Role::class);
    }

    public function index()
    {
        $roles = Role::with('permissions')->get();

        return view('roles.index', compact('roles'));
    }

    public function create()
    {
        $abilities = Permission::all();

        return view('roles.create', compact('abilities'));
    }

    public function store(RoleRequest $request, Role $role)
    {
        $role = Role::create($request->only('name'));

        $role->syncPermissions($request->input('permissions'));

        flash()->success('Successfully created the role');

        return redirect()->route('roles.index');
    }

    public function edit(Role $role)
    {
        $role->load('permissions');

        $abilities = Permission::all();

        return view('roles.edit', compact('role', 'abilities'));
    }

    public function update(RoleRequest $request, Role $role)
    {
        $role->update($request->only('name'));

        $role->syncPermissions($request->input('permissions'));

        flash()->success('Successfully updated the role');

        return redirect()->route('roles.index');
    }

    public function destroy(Role $role)
    {
        $role->delete();

        flash()->success('Successfully deleted the role');

        return redirect()->route('roles.index');
    }
}

resources/views/roles/create.blade.php
@extends('layouts.app')

@section('title', __('Create a New Role'))

@section('content')
  <form action="{{ route('roles.store') }}" method="post">
    @csrf
    <div class="row">
      <div class="col-lg-6">
        <div class="card-box">

          <div class="dropdown float-right">
            <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown" aria-expanded="false">
              <i class="mdi mdi-dots-vertical"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <!-- item-->
              <button type="submit" class="dropdown-item">Save</button>
            </div>
          </div>

          <h4 class="header-title mt-0">Role Detail</h4>

          <p class="text-muted font-13">Type a role name that describes the permissions granted.</p>

          <div class="row">
            <div class="col-lg-8">
              <div class="form-group">
                <label for="name" class="control-label">Name</label>
                <input type="text" id="name" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}">
                @error('name')
                  <div class="invalid-feedback">
                    {{ $message }}
                  </div>
                @enderror
              </div>
            </div>
          </div>

          <h4 class="header-title mt-3">Permissions</h4>

          <p class="text-muted font-13">Choose the abilities for this role.</p>

          @if ($abilities->isEmpty())
            <div class="alert alert-warning text-center">
              There are no capabilities available. Please define capabilities in the <code>permissions</code> table.
            </div>
          @else
            @foreach ($abilities as $ability)
              <div class="custom-control custom-switch mb-2">
                <input type="checkbox" class="custom-control-input"
                       id="ability-{{ $ability->id }}"
                       name="permissions[]"
                       value="{{ $ability->id }}"
                       {{ old('permissions.' . $loop->index) == $ability->id ? 'checked' : '' }}
                >
                <label class="custom-control-label" for="ability-{{ $ability->id }}">{{ $ability->name }}</label>
              </div>
            @endforeach
          @endif
        </div>
      </div>
    </div>
  </form>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')

@section('title', $role->name)

@section('content')
  <form action="{{ route('roles.update', $role) }}" method="post">
    @csrf
    @method('PUT')
    <div class="row">
      <div class="col-lg-6">
        <div class="card-box">
          <h4 class="header-title mt-0">Edit Role</h4>

          <p class="text-muted font-13">Type a role name that describes the permissions granted.</p>

          <div class="row">
            <div class="col-8">
              <div class="form-group">
                <label for="name" class="control-label">Name</label>
                <input type="text" id="name" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name', $role->name) }}">
                @error('name')
                  <div class="invalid-feedback">
                    {{ $message }}
                  </div>
                @enderror
              </div>
            </div>
          </div>

          <h4 class="header-title mt-3">Permissions</h4>

          <p class="text-muted font-13">Choose the abilities for this role.</p>

          @if ($abilities->isEmpty())
            <div class="alert alert-warning text-center">
              There are no capabilities available. Please define capabilities in the <code>permissions</code> table.
            </div>
          @else
            @foreach ($abilities as $ability)
              <div class="custom-control custom-switch mb-2">
                <input type="checkbox" class="custom-control-input"
                       id="ability-{{ $ability->id }}"
                       name="permissions[]"
                       value="{{ $ability->id }}"
                       {{ $role->hasPermissionTo($ability) ? 'checked' : '' }}
                >
                <label class="custom-control-label" for="ability-{{ $ability->id }}">{{ $ability->name }}</label>
              </div>
            @endforeach
          @endif

          <button type="submit" class="btn btn-primary mt-3">Save</button>
        </div>
      </div>
    </div>
  </form>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')

@section('title', __('Role Management'))

@section('content')
  <div class="row">
    <div class="col-lg-12">
      <div class="card-box">

        <div class="dropdown float-right">
          <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown" aria-expanded="false">
            <i class="mdi mdi-dots-vertical"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <!-- item-->
            <a href="{{ route('roles.create') }}" class="dropdown-item">Create a New Role</a>
          </div>
        </div>

        <h4 class="header-title mt-0">Role Management</h4>

        <p class="text-muted font-13">List of user roles.</p>

        <p class="alert alert-info">The authority of each user can be determined the ability to access various features in the application.</p>
      </div>
    </div>
  </div>

  <div class="row">
    @foreach ($roles as $role)
      <div class="col-lg-3">
        <div class="card-box">

          @canany(['update', 'delete'], $role)
            <div class="dropdown float-right">
              <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown" aria-expanded="false">
                <i class="mdi mdi-dots-vertical"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                @can('update', $role)
                  <a href="{{ route('roles.edit', $role) }}" class="dropdown-item">Edit Permissions</a>
                @endcan

                @can('delete', $role)
                  <div class="dropdown-divider"></div>
                  <a href="{{ route('roles.destroy', $role) }}" class="dropdown-item text-danger" data-method="delete" data-confirm="Are you sure?">Delete</a>
                @endcan
              </div>
            </div>
          @endcanany

          <h4 class="header-title mt-0">{{ $role->name }}</h4>

          <p>{{ trans_choice('roles.abilities-count', $role->permissions->count(), ['count' => $role->permissions->count()]) }}</p>
        </div>
      </div>
    @endforeach
  </div>
@endsection